version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - klique-testbench

  springbootapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - klique-testbench

networks:
  klique-testbench:
    driver: bridge
